SolClienteRazor/ClienteRazor/Models/ErrorViewModel.cs
namespace ClienteRazor.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SolClienteRazor/ClienteRazor/Models/VmJobs.cs
namespace ClienteRazor.Models
{
    public class VmJobs
    {
        public short Id { get; set; }
        public string? JobDesc { get; set; }
        public byte? MinLev { get; set; }

        public byte? MaxLev { get; set; }
    }
}

SolClienteRazor/ClienteRazor/Models/publisher.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ClienteRazor.Models
{
    public class publisher
    {
        [Key]
        [StringLength(4)]
        [DisplayName("Id")]
        public string? pub_id { get; set; }
        [StringLength(40)]
        [DisplayName("Nombre")]
        public string? pub_name { get; set; }
        [StringLength(20)]
        [DisplayName("Ciudad")]
        public string? city { get; set; }
        [StringLength(30)]
        [DisplayName("Estado")]
        public string? state { get; set; }
        [StringLength(30)]
        [DisplayName("Pais")]
        public string? country { get; set; }
    }
}

SolClienteRazor/ClienteRazor/Controllers/EnviosController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ClienteRazor.Models;

namespace ClienteRazor.Controllers
{
    public class EnviosController : Controller
    {
        //endpoint
        string strURL = "https://localhost:7193/api/publishers";
        // una instancia de la clase HttpClient
        HttpClient cliente = new HttpClient();

        public async Task<IActionResult> Index()
        {
            var listaPublishers = JsonConvert.DeserializeObject<List<publisher>>
                (await cliente.GetStringAsync(strURL)).ToList();

            return View(listaPublishers);
        }

        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Agregar(publisher publisher)
        {
            // llamo al servicio de la api REST

            await cliente.PostAsJsonAsync(strURL, publisher);
            return RedirectToAction("Index");
        }
    }
}

SolClienteRazor/ClienteRazor/Controllers/HomeController.cs
using ClienteRazor.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ClienteRazor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SolClienteRazor/ClienteRazor/Views/Envios/Agregar.cshtml
@model ClienteRazor.Models.publisher

@{
    ViewData["Title"] = "Agregar";
}

<h1>Agregar nuevo pub</h1>

<h4> </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Agregar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="pub_id" class="control-label"></label>
                <input asp-for="pub_id" class="form-control" />
                <span asp-validation-for="pub_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="pub_name" class="control-label"></label>
                <input asp-for="pub_name" class="form-control" />
                <span asp-validation-for="pub_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="city" class="control-label"></label>
                <input asp-for="city" class="form-control" />
                <span asp-validation-for="city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="state" class="control-label"></label>
                <input asp-for="state" class="form-control" />
                <span asp-validation-for="state" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="country" class="control-label"></label>
                <input asp-for="country" class="form-control" />
                <span asp-validation-for="country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Enviar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SolClienteRazor/ClienteRazor/Views/Envios/Index.cshtml
@model IEnumerable<ClienteRazor.Models.publisher>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de pubs</h1>

<p>
    <a asp-action="Agregar">Nuevo </a>
</p>
<table class="table">
    <thead>
        <tr>
@*            <th>
                @Html.DisplayNameFor(model => model.pub_id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.pub_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.city)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.state)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
@*            <td>
                @Html.DisplayFor(modelItem => item.pub_id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.pub_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.state)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.country)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Detalles", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Borrar", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

SolClienteRazor/ClienteRazor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SolClienteRazor/ClienteRazor/Views/ListaJobsController1/Index.cshtml
@model IEnumerable<ClienteRazor.Models.VmJobs>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">ListaJobs</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobDesc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MinLev)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxLev)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobDesc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MinLev)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxLev)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

SolClienteRazor/ClienteRazor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClienteRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClienteRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClienteRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Envios" asp-action="Index">Fletes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ListaJobsController1" asp-action="Index">Lista de Jobs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ClienteRazor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>